function [methodinfo,structs,enuminfo,ThunkLibName]=mxsmp
%MXSMP Create structures to define interfaces found in 'libsmp_x64'.

%This function was generated by loadlibrary.m parser version  on Thu Apr  6 14:19:28 2017
%perl options:'libsmp_x64.i -outfile=mxsmp.m -thunkfile=libsmp_x64_thunk_pcwin64.c -header=libsmp_x64.h'
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'libsmp_x64_thunk_pcwin64');
%  void libsmp_addReceivedBytes ( const uint8_t * bytes , uint32_t length ); 
fcns.thunkname{fcnNum}='voidvoidPtruint32Thunk';fcns.name{fcnNum}='libsmp_addReceivedBytes'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'uint8Ptr', 'uint32'};fcnNum=fcnNum+1;
%  size_t libsmp_bytesMessagesToReceive (); 
fcns.thunkname{fcnNum}='uint64Thunk';fcns.name{fcnNum}='libsmp_bytesMessagesToReceive'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='uint64'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  uint16_t libsmp_getNextReceivedMessageLength (); 
fcns.thunkname{fcnNum}='uint16Thunk';fcns.name{fcnNum}='libsmp_getNextReceivedMessageLength'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='uint16'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  uint8_t libsmp_getReceivedMessage ( message_t * msg ); 
fcns.thunkname{fcnNum}='uint8voidPtrThunk';fcns.name{fcnNum}='libsmp_getReceivedMessage'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='uint8'; fcns.RHS{fcnNum}={'message_tPtr'};fcnNum=fcnNum+1;
%  size_t libsmp_getMessagesToSend (); 
fcns.thunkname{fcnNum}='uint64Thunk';fcns.name{fcnNum}='libsmp_getMessagesToSend'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='uint64'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  uint16_t libsmp_getNextMessageLength (); 
fcns.thunkname{fcnNum}='uint16Thunk';fcns.name{fcnNum}='libsmp_getNextMessageLength'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='uint16'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  uint8_t libsmp_getMessage ( message_t * msg ); 
fcns.thunkname{fcnNum}='uint8voidPtrThunk';fcns.name{fcnNum}='libsmp_getMessage'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='uint8'; fcns.RHS{fcnNum}={'message_tPtr'};fcnNum=fcnNum+1;
%  uint32_t libsmp_sendBytes ( const uint8_t * bytes , uint32_t length ); 
fcns.thunkname{fcnNum}='uint32voidPtruint32Thunk';fcns.name{fcnNum}='libsmp_sendBytes'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='uint32'; fcns.RHS{fcnNum}={'uint8Ptr', 'uint32'};fcnNum=fcnNum+1;
%  void libsmp_useRS ( BOOL rs ); 
fcns.thunkname{fcnNum}='voidint32Thunk';fcns.name{fcnNum}='libsmp_useRS'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}=[]; fcns.RHS{fcnNum}={'int32'};fcnNum=fcnNum+1;
structs.message_t.members=struct('message', 'uint8#65536', 'size', 'uint32');
methodinfo=fcns;